### ISSUE TITLE
Getting RETRIEVE_HOST/PORT for our scripts?

### ISSUE THREAD

**Issue by noahpresler** [knowledge-discovery/hw1#1]
In the eval.sh we can on line 29 the following:

`#run a container of the token-counter image with its default CMD and info about the retriever container
docker run --rm -e ${RETRIEVE_HOST} -e ${RETRIEVE_PORT} token-counter`

How do we get RETRIEVE_HOST and RETRIEVE_PORT now from our Python script? 
I'd Imagine in our Dockerfile we'd just run a python script with these two arguments as parameters similar to how you are doing so on the slides. However, when I echo $RETRIEVE_HOST or ${RETRIEVE_HOST} in the dockerfile, I don't get anything back.

Is this the wrong approach?

**Comment by TomLippincott** [comment]
Oops, that's a mistake: the -e values shouldn't be inside ${}.  Fixed now.

**Comment by noahpresler** [comment]
Hmm this still doesn't seem to work for me.

**Comment by noahpresler** [comment]
I was able to get it echoing localhost with the following

**eval.sh**
`#!/bin/bash

if [[ ! -e $1 || -z $1 ]]
then
    echo "Please provide a tar file of Communications as an argument"
    exit 1
fi

EXPANDED=`realpath ${1}`
DATAPATH=`dirname ${EXPANDED}`
DATAFILE=`basename ${EXPANDED}`

# pull base image and Retriever image from Docker hub
docker pull hltcoe/concrete
docker pull hltcoe/tar-retriever

# build your image to count tokens
docker build --force-rm -t token-counter .

# run a daemonized container of the retriever image, serving data from the specified file on container port 9090
docker run -d --name retriever -p 9090 -v ${DATAPATH}:/data hltcoe/tar-retriever python /tmp/scripts/retrieve-server.py -i /data/${DATAFILE} -p 9090

# the retriever container we just started is running on the localhost
RETRIEVE_HOST=localhost

# determine what random port on the host was mapped to port 9090 on the container
RETRIEVE_PORT=`docker inspect --format '{{(index (index .NetworkSettings.Ports "9090/tcp") 0).HostPort}}' retriever`

# run a container of the token-counter image with its default CMD and info about the retriever container
docker run --rm -e RETRIEVE_HOST=$RETRIEVE_HOST -e RETRIEVE_PORT=$RETRIEVE_PORT token-counter

#
# At this point, the script should print out the number of unique and total tokens in the data file, e.g.:
#
#   Unique: 2341 Total: 10032
#

# stop and remove the retriever container
docker rm -f retriever
`

**Dockerfile**
`FROM hltcoe/concrete
MAINTAINER Noah Presler <noah@presler.me>
LABEL Description="Homework 1 - Unique Token Counter"

WORKDIR /tmp

ENTRYPOINT echo "HII  $RETRIEVE_HOST"`

**Comment by TomLippincott** [comment]
Nice work!  I've fixed it with a slightly different approach: adding `export` before the initial variable assignments.
