### ISSUE TITLE
running dummyqueryhandlerlauncher

### ISSUE THREAD

**Issue by baekchun** [knowledge-discovery/hw1#13]
Hi,

After I compiled the project directory using maven, I tried to run it using the command : java -cp target/*.jar edu.jhu.hlt.kdft.hw1.DummyQueryHandlerLauncher 

Although the above command worked for another test java file I created, for the dummyqueryhandlerlauncher class, it doesn't work, saying the following: Error: Could not find or load main class edu.jhu.hlt.kdft.hw1.DummyQueryHandlerLauncher

**Comment by TomLippincott** [comment]
You should bear in mind that the way the stub code is tested and run is within Docker images: check out the README.md file in the stub search directory.  The way it's being invoked there, within the Docker container, is what's supposed to work out-of-the-box: we can't debug the Maven/Pip/etc setups on different people's laptops.  If you go the route of running things outside of Docker images, I suggest you look carefully for *why* it works in one context but not another.  This sort of debugging is very important in real-world engineering.
