### ISSUE TITLE
Python print(output) arabic words backward 

### ISSUE THREAD

**Issue by sing0627** [knowledge-discovery/hw1#14]
Hello I'm having an issue where when the token is Arabic, it prints my output file in backwards. 
Here is an example :
<img width="696" alt="screen shot 2016-09-24 at 9 29 16 pm" src="https://cloud.githubusercontent.com/assets/11038454/18812327/7a4dfbf6-829e-11e6-9d67-ba82b7ea857f.png">

Is there a reason? and also is it okay to print it in this way? The tokens are already encoded to "utf-8"

Thank you!

**Comment by ctongfei** [comment]
Arabic is written right-to-left. This is the expected behavior.

-- Tongfei (from mobile)

**Comment by sing0627** [comment]
Thank you.

**Comment by ctongfei** [comment]
Are you using the Python shell? If so then it's ok

-- Tongfei (from mobile)

**Comment by sing0627** [comment]
Yes I was using Python shell

**Comment by ctongfei** [comment]
I've observed this behavior before. It is a bug of the py shell

-- Tongfei (from mobile)

**Comment by lwolfsonkin** [comment]
Which os and terminal program are you using? I've found that it depends highly. The default mac terminal correctly displays right to left text (I tested it with Hebrew), but iTerm for mac doesn't. @sing0627
