### ISSUE TITLE
Outputs

### ISSUE THREAD

**Issue by emarsh12** [knowledge-discovery/hw1#16]
Do you want the number id or title returned for the search results communicationId? (ex. 49099833 or 'Rocket Science')?

**Comment by vandurme** [comment]
Title

**Comment by TomLippincott** [comment]
@knowledge-discovery/cs365-fall-2016 
Just to clarify: in all cases you should be using/returning the communication.id: in the case of Wikipedia data, this happens to be the article title (e.g. "Naim_Tulu") while in Twitter it's the numeric tweet ID (but still a string).  Just use what's there!
