### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by lwolfsonkin** [knowledge-discovery/hw1#18]
Wondering, are we allowed to use Python 3 instead, because I'm getting some annoying `unicode` issues, and those would all cease if we were using python 3. I guess a better reformulation of the question would be, does `concrete-python` support python 3?

**Comment by TomLippincott** [comment]
I think it's pretty unlikely that it supports python 3: it *is* possible to avoid encoding issues with python 2 by making careful use of codecs.getreader("utf-8")/getwriter("utf-8") in the appropriate places.
