### ISSUE TITLE
Names of communications

### ISSUE THREAD

**Issue by ecalder6** [knowledge-discovery/hw1#4]
What are the names of communications? From [here](http://www.cs.jhu.edu/~tom/concrete/communication.html), it seems that the id has name, but from what I observed id is an integer. If it is, do we need to sort lexicographically?

**Comment by TomLippincott** [comment]
@knowledge-discovery/cs365-fall-2016 
Still sort lexicographically: remember also that it only so happens that the Communications in test_data.tgz are tweets, and so their commids are twitter (numeric) IDs.  But we will run your code over other data sets: in fact, this week we'll point you to the Wikipedia data Aaron used in his lecture, and you can test on that as well.
