### ISSUE TITLE
Filter top 500 or 250

### ISSUE THREAD

**Issue by ecalder6** [knowledge-discovery/hw1#5]
eval.sh says we should filter top 500, but the README says we should filter top 250.

**Comment by TomLippincott** [comment]
@knowledge-discovery/cs365-fall-2016 
The typo's in eval.sh: it should be 250.  Fixed.

**Comment by lwolfsonkin** [comment]
When you say 'filter top 250', it's filter the top 250 by what criterion?

**Comment by TomLippincott** [comment]
250 most frequent.

**Comment by lwolfsonkin** [comment]
That is, the 250 words with the highest document frequencies? Or with highest frequency, period? Meaning, the ones that occurred the most often across all documents: sum across all documents the number of times a particular type occurs?, and sort by that?

**Comment by TomLippincott** [comment]
Yes, highest total frequency.  These are likely to be stop-words, punctuation, and so forth.

**Comment by lwolfsonkin** [comment]
Gotcha. Thanks so much!

**Comment by vandurme** [comment]
Yes, highest TF.  You would expect though that these will highly correlate: hard to be the most frequent word without appearing in a lot of documents!

**Comment by sing0627** [comment]
Also just to make sure, does top 50 out of 250 mean top 50 in terms of TF or IDF ? Thank you in advance.

**Comment by TomLippincott** [comment]
Top 50 (and 250) in terms of *overall* TF: i.e., summed over all documents, not any particular document's TF.
